# Generated by Django 5.2.9 on 2025-12-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('on_site_time', models.CharField(max_length=100)),
                ('deliverable', models.CharField(max_length=200)),
                ('raw', models.BooleanField(default=False)),
                ('vid_preview', models.BooleanField(default=False)),
                ('drone', models.BooleanField(default=False)),
                ('second_photographer', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PricingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('packages', models.ManyToManyField(related_name='guides', to='packages.package')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
