# Generated by Django 5.2.9 on 2025-12-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='photo_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingguide',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='guides', to='gallery.photo'),
        ),
        migrations.AlterField(
            model_name='pricingguide',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='guides', to='packages.package'),
        ),
    ]
